name: Maven CI

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [ '21' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Show tool versions
        run: |
          java -version
          mvn -v

      - name: Build & Test
        run: mvn -B clean verify --no-transfer-progress -Djava.runtime.version=${{ matrix.java }}
